---
apiVersion: v1
kind: Service
metadata:
  name: application-db
spec:
  type: NodePort  # Add this line to expose using NodePort
  selector:
    app: application-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001  # Choose a port within the valid NodePort range (30000–32767)
---
apiVersion: v1
kind: Service
metadata:
  name: application-demo
spec:
  type: NodePort  # Change this to NodePort to expose using NodePort instead of LoadBalancer
  selector:
    app: application-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort  # Change this to NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: NodePort  # Change this to NodePort
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
spec:
  type: NodePort  # Change this to NodePort
  selector:
    app: promtail
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 30005
