apiVersion: v1
kind: Service
metadata:
  name: application-db
spec:
  selector:
    app: application-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: application-demo
spec:
  selector:
    app: application-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
